version: "3"
services:

  web:
      build: ./loopback_chatbot/
      environment:
      - NODE_ENV=production
      ports:
      - "3000"
      networks:
      - "reswork"
      command: ["./wait-for-it.sh", "db:3306", --, "npm", "start"]
  db:
      image: mysql:5.7
      ports:
      - "3306"
      networks:
      - "reswork"
      volumes: 
      - lex-data:/var/lib/mysql
      restart: always
      environment:
          MYSQL_ROOT_PASSWORD: MysqlRootPassword
          MYSQL_DATABASE: DatabaseName
          MYSQL_USER: MysqlUserName
          MYSQL_PASSWORD: MysqlPassword
  nginx-reverse-proxy:
      image: nginx:alpine
      ports:
      - "80:80"
      - "443:443"
      networks:
      - "reswork"
      ## Change the file path by switching the words dev and prod to fit your deployment stage.
      volumes:
      - ./nginx_reverse_proxy/dev/nginx.conf:/etc/nginx/nginx.conf
      ## Uncomment the following line in order to access ssl keys in production environment.
      ##- /etc/letsencrypt/:/etc/letsencrypt/
networks:
  reswork:

volumes:
  lex-data:
      
